### ISSUE TITLE
Missing google-services.json

### ISSUE THREAD

**Issue by rcampbell95** [rcampbell95/MunchieMatch#4]
Hey @brentjsimon, I pulled the latest commit in the login_screen branch and when I tried to run it I received this error:  

`Error:Execution
 failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  C:\Users\rober\Documents\Mobile Projects\MunchieMatch\app\src\debug\google-services.json
  C:\Users\rober\Documents\Mobile Projects\MunchieMatch\app\google-services.json`

**Comment by brentjsimon** [comment]
@rcampbell95 Below I have attached the google-services.json file. This should go under Project tab >app folder
![munchiematchgoogleservicesjsonhelp](https://cloud.githubusercontent.com/assets/23416467/24078112/59acab88-0c21-11e7-8576-cf962bc1f4f1.JPG)
 

[googleservices.json.zip](https://github.com/rcampbell95/MunchieMatch/files/853016/googleservices.json.zip)
